/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

export function main() {
  const upperBound = 4000000;
  let keepGoing = true;
  let previousTwo = [0, 1];
  let currentTerm = 0;
  let sum = 0;
  let iterations = 0;

  while (keepGoing) {
    iterations++;
    if (currentTerm >= upperBound) {
      keepGoing = false;
      continue;
    }

    currentTerm = previousTwo[0] + previousTwo[1];
    previousTwo[0] = previousTwo[1];
    previousTwo[1] = currentTerm;
    if (currentTerm % 2 === 0) {
      sum += currentTerm;
    }
  }
  console.log(
    `Results:\nIterations: ${iterations}\ncurrentTerm: ${currentTerm}\nsum: ${sum}`
  );
}

main();
